# frozen_string_literal: true

# UserRegistrationService handles the complete user registration flow:
# 1. Creates the user account
# 2. Auto-generates an organization for the user
# 3. Creates organization membership (user as owner)
# 4. Creates organization configuration with defaults
#
# This ensures every new user has a complete setup and can immediately
# access the platform without additional onboarding steps.
#
# Usage:
#   user = User.new(user_params)
#   result = UserRegistrationService.call(user)
#   if result.success?
#     # User and organization created successfully
#     organization = result.organization
#   else
#     # Handle errors - user.errors will contain validation errors
#   end
class UserRegistrationService
  attr_reader :user, :organization, :errors

  def self.call(user)
    new(user).call
  end

  def initialize(user)
    @user = user
    @organization = nil
    @errors = []
  end

  def call
    ActiveRecord::Base.transaction do
      # Step 1: Save the user
      unless user.save
        @errors = user.errors.full_messages
        raise ActiveRecord::Rollback
      end

      # Step 2: Create organization with auto-generated name
      @organization = create_organization
      unless @organization.persisted?
        @errors = @organization.errors.full_messages
        raise ActiveRecord::Rollback
      end

      # Step 3: Create organization membership (user as owner)
      membership = create_membership
      unless membership.persisted?
        @errors = membership.errors.full_messages
        raise ActiveRecord::Rollback
      end

      # Step 4: Create organization configuration with defaults
      config = create_organization_configuration
      unless config.persisted?
        @errors = config.errors.full_messages
        raise ActiveRecord::Rollback
      end
    end

    self
  end

  def success?
    errors.empty? && user.persisted? && organization&.persisted?
  end

  private

  def create_organization
    Organization.create(
      name: generate_organization_name,
      status: "active"
      # slug will be auto-generated by the Organization model's before_validation callback
    )
  end

  def create_membership
    # We need to bypass tenant requirement when creating the membership
    # because OrganizationMembership has acts_as_tenant :organization
    ActsAsTenant.without_tenant do
      OrganizationMembership.create(
        user: user,
        organization: organization,
        role: "owner"
      )
    end
  end

  def create_organization_configuration
    OrganizationConfiguration.create(
      organization: organization
      # contexts_config and features_config will be set by the model's before_validation callback
    )
  end

  def generate_organization_name
    # Generate a friendly organization name based on user's name
    # Examples: "David's Organization", "John's Organization"
    "#{user.first_name}'s Organization"
  end
end

