# Exported from Render on 2026-03-09T09:32:28Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: make_ai_great_again
      runtime: ruby
      repo: https://github.com/DavidGeismarLtd/make_ai_great_again
      plan: starter
      envVars:
      - key: REDIS_URL
        fromService:
          name: make-ai-great-again-redis
          type: keyvalue
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: make-ai-great-again-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
      region: frankfurt
      buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec
        rake assets:clean;
      startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
      autoDeployTrigger: commit
    - type: worker
      name: make_ai_great_again_sidekiq_worker
      runtime: docker
      repo: https://github.com/DavidGeismarLtd/make_ai_great_again
      buildCommand: bundle install
      startCommand: bundle exec sidekiq -C config/sidekiq.yml
      plan: starter
      envVars:
      - key: REDIS_URL
        fromService:
          name: make-ai-great-again-redis
          type: keyvalue
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: make-ai-great-again-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
      region: frankfurt
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
    - type: keyvalue
      name: make-ai-great-again-redis
      plan: free
      region: frankfurt
      maxmemoryPolicy: allkeys-lru
      ipAllowList: []
    databases:
    - name: make-ai-great-again-db
      databaseName: make_ai_great_again_db
      user: make_ai_great_again_db_user
      plan: basic-256mb
      region: frankfurt
      ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
      postgresMajorVersion: "18"
      diskSizeGB: 1
